builds:
  - main: ./cmd/gitprompt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

brews:
  - tap:
      owner: abhinav
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_msg_template: "{{ .ProjectName }}: Update formula to {{ .Tag }}"
    commit_author:
      name: Abhinav Gupta
      email: 41730+abhinav@users.noreply.github.com
    homepage: https://github.com/abhinav/gitprompt
    description: " Informative git prompt for zsh and bash"
    license: "MIT"
    skip_upload: auto
    dependencies:
      - name: git

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-dev"

changelog:
  # A commit log is not a changelog.
  skip: true
